"""rename title to task in todos

Revision ID: 8601290fe791
Revises: 7235977f8142
Create Date: 2026-01-05 14:58:02.436487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8601290fe791'
down_revision: Union[str, Sequence[str], None] = '7235977f8142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('task', sa.String(), nullable=False))
    op.drop_column('todos', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('todos', 'task')
    # ### end Alembic commands ###
